language: cpp

os:
  - linux
  - osx

compiler:
    - gcc
    - clang

addons:
  apt:
    packages:
    - libopencv-dev

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                                                                               ;fi
  #remove numpy installed by pip, incompatible with opencv
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then /usr/bin/yes | pip uninstall numpy                                                        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install opencv                                                                       ;fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget --no-check-certificate http://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xzf cmake-3.8.0-Linux-x86_64.tar.gz                                                  ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PWD/cmake-3.8.0-Linux-x86_64/bin:$PATH                                       ;fi

script:
  - mkdir build && cd build && cmake .. && cmake --build .
