language: cpp

env:
  global:
    - OPENCV_VERSION=3.2.0
    - OPENCV_INSTALL_DIR="$HOME/opencv-$OPENCV_VERSION-install"
    - LD_LIBRARY_PATH="$OPENCV_INSTALL_DIR/lib"
    - PKG_CONFIG_PATH="$OPENCV_INSTALL_DIR/lib/pkgconfig"

os:
  - linux
  - osx

compiler:
    - gcc
    - clang

addons:
  apt:
    packages:
    - libopencv-dev
    - libboost-all-dev

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                                                                               ;fi
  #remove numpy installed by pip, incompatible with opencv
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then /usr/bin/yes | pip uninstall numpy                                                        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install opencv                                                                       ;fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget --no-check-certificate http://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xzf cmake-3.8.0-Linux-x86_64.tar.gz                                                  ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PWD/cmake-3.8.0-Linux-x86_64/bin:$PATH                                       ;fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/opencv/opencv/archive/$OPENCV_VERSION.tar.gz -O opencv-$OPENCV_VERSION.tar.gz ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xzf opencv-$OPENCV_VERSION.tar.gz                                                     ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm opencv-$OPENCV_VERSION.tar.gz                                                          ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd opencv-$OPENCV_VERSION                                                                 ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir build                                                                               ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd build                                                                                  ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DWITH_CUDA=OFF -DENABLE_AVX=ON -DWITH_OPENGL=ON -DWITH_TBB=ON -DBUILD_opencv_apps=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX="$OPENCV_INSTALL_DIR" -DPYTHON3_EXECUTABLE=$(which python3) -DPYTHON3_INCLUDE_DIR=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") .. ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j2                                                                                  ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make install                                                                              ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../..                                                                                  ;fi


script:
  - mkdir build && cd build && cmake .. && cmake --build .
